services:
    database:
     container_name: database_infopanel
     image: mysql:8.0
     command: --default-authentication-plugin=mysql_native_password
     restart: always
     environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
     ports:
      - "4306:3306"
     volumes:
      - ./.development/mysql:/var/lib/mysql
     networks:
     - symfony

    php:
     container_name: backend_infopanel
     build:
      context: ./backend
     ports:
     - '9000:9000'
     restart: always
     volumes:
     - ./backend:/var/www/backend
     depends_on:
     - database
     networks:
     - symfony
    
    frontend:
     container_name: frontend_infopanel
     build:
      context: ./frontend
      dockerfile: Dockerfile_prod
     ports: 
      - '5173:5173'
     volumes:
      - ./frontend:/var/www/
     depends_on:
     - php
     networks:
     - symfony 

    nginx:
     container_name: nginx
     image: nginx:stable-alpine
     ports:
     - '8080:80'
     restart: always
     volumes:
     - ./frontend:/var/www/frontend
     - ./backend:/var/www/backend
     - ./.development/nginx/default.conf:/etc/nginx/conf.d/default.conf
     depends_on:
     - php
     - database
     - frontend
     networks:
     - symfony
    
    httpd:
     container_name: httpd_infopanel
     ports:
     - '80:80'
     volumes:
     - ./frontend/dist:/usr/local/apache2/htdocs/
     image: 'httpd:latest'
     restart: always
     networks:
     - symfony

networks:
  symfony:
    driver: bridge