<<<<<<< HEAD
services:
    database:
     container_name: database_infopanel
=======
version: "3.8"
services:
    database:
     container_name: database_symfony
>>>>>>> 9b759b1b08d3ad44bc33ec046c0bd9690f899810
     image: mysql:8.0
     command: --default-authentication-plugin=mysql_native_password
     restart: always
     environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
     ports:
      - "4306:3306"
     volumes:
      - ./.development/mysql:/var/lib/mysql
<<<<<<< HEAD
     networks:
      - symfony
    
    frontend:
     container_name: frontend_infopanel
     build:
      context: ./frontend
     ports: 
      - '80:5173'
     volumes:
      - ./frontend/node_modules:/var/www/node_modules
      - ./frontend:/var/www
     depends_on:
     - php 
     networks:
     - symfony 

    php:
     container_name: backend_infopanel
     build:
      context: ./backend
     restart: always
     ports:
     - '9000:9000'
     volumes:
     - ./backend:/var/www/backend
     depends_on:
     - database
     networks:
     - symfony

=======
    php:
     container_name: php
     build:
      context: ./.development/php
     ports:
     - '9000:9000'
     volumes:
     - ./app:/var/www/symfony_docker
     depends_on:
     - database
>>>>>>> 9b759b1b08d3ad44bc33ec046c0bd9690f899810
    nginx:
     container_name: nginx
     image: nginx:stable-alpine
     ports:
<<<<<<< HEAD
     - '8080:80'
     restart: always
     volumes:
     - ./backend:/var/www/backend
     - ./.development/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
     depends_on:
     - php
     - database
     networks:
     - symfony

networks:
  symfony:
    driver: bridge

#volumes:
#  app_node_modules:
=======
     - '80:80'
     volumes:
     - ./app:/var/www/symfony_docker
     - ./.development/nginx/default.conf:/etc/nginx/conf.d/default.conf
     depends_on:
     - php
     - database
>>>>>>> 9b759b1b08d3ad44bc33ec046c0bd9690f899810
